### ISSUE TITLE
Cannot Open the google colab 

### ISSUE THREAD

**Issue by yeongnamtan** [augmentedstartups/AS-One#10]
can't open google colab

**Comment by lorenzlorg** [comment]
I have no problems opening it, try it again.

https://colab.research.google.com/drive/19noVn6S0I0I7Uh0cVNEroYTmQaWDifun?authuser=1#scrollTo=q2M6h7caeSq0

**Comment by augmentedstartups** [comment]
Try this link also https://drive.google.com/file/d/1xy5P9WGI19-PzRH3ceOmoCgp63K6J_Ls/view?usp=sharing
