### ISSUE TITLE
How to set a custom path for downloaded weights ?

### ISSUE THREAD

**Issue by franklinkemta** [augmentedstartups/AS-One#12]
Hello guys, Thank you for such amazing work!

Is there a way to specify a custom path for downloaded weights instead of the current working dir ?
_e.g:_ to be able to use the Tracker this way 

Tracker(asone.BYTETRACK, _model_, use_cuda=False,  **custom_model_path**)

in case the **custom_model_path** already exists the **.pts** are loaded from that path (the same way it's downloaded to the working dir at the moment).

Thanks

**Comment by MNMaqsood** [comment]
#5
